spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/querydsl
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
    # show_sql: true
        format_sql: true
  data:
    web:
      pageable:
        default-page-size: 10

#        띄어스기 2번임data.web.pageable.default-page-size=20
logging.level:
  org.hibernate.SQL: debug
